sait/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sait_app import urls

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url('^blog_app/', include(urls)),
    url(r'^admin/', include(admin.site.urls)),
]

sait_app/urls.py
from django.conf.urls import url
from sait_app import views


urlpatterns = [
    url(r'^$', views.page_start, name="page_start"),
    url(r'about_me/$', views.page_about_me, name="page_about_me"),
    url(r'contacts/$', views.page_contacts, name="page_contacts"),
    url(r'home/$', views.page_home, name="page_home"),
    url(r'article/$', views.page_article, name="page_article"),
    url(r'article/(\d{1,2})/$', views.detail, name="detail"),
    url(r'media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': './media/'}),
    url(r'^detail_coment/(\d{8,})/(\d{1,})/$', views.detail_coment, name="detail_coment"),
]

sait_app/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Article(models.Model):
    article_title = models.CharField(max_length=255, verbose_name="Заголовок")
    article_text = models.TextField(max_length=1000, verbose_name="Статья")
    date_publication = models.DateField(blank=True, null=True, verbose_name="дата публикации")

    def __unicode__(self):
        return '%s' % (self.article_title)


class Coments(models.Model):
    autor_coment = models.CharField(max_length=20, verbose_name="Имя")
    mail_autor_coment = models.EmailField(verbose_name="Почта")
    coment_text = models.TextField(max_length=1000, verbose_name="Коментарий")
    date_coment = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article)
    parent = models.ForeignKey('self', blank=True, null=True)
    path = models.TextField(max_length=800, blank=True)

    def __unicode__(self):
        return '%s' % (self.autor_coment)

    def save(self):
        super(Coments, self).save()
        if not self.path:
            if self.parent:
                try:
                    parentt = self.parent
                    parent_path = parentt.path
                except:
                    parent_path = ''
                self.path = '%s%08d' % (parent_path, self.id)
            else:
                self.path = '%08d' % self.id
            super(Coments, self).save()

    @property
    def level(self):
        return max(0, (len(self.path))/8)

    @property
    def html_level(self):
        return (self.level - 1) * 20

    @property
    def html_level_full(self):
        return (self.html_level - 300) / 2

sait_app/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from sait_app.models import Article,  Coments
from sait_app.form import ComentsForm
from django.template import RequestContext
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.http import Http404, JsonResponse, HttpResponseRedirect
import datetime


def all_paginator(request, paginator):
    page = request.GET.get('page')

    try:
        any_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        any_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        any_page = paginator.page(paginator.num_pages)
    return {'page': any_page}


def page_article(request):

    now = datetime.date.today()
    ordering = request.GET.get("sort", "date_publication")
    valid_ordering = {"coments__count", "date_publication", "-coments__count", "-date_publication"}
    ordering = ordering if ordering in valid_ordering else "date_publication"
    queryset = Article.objects.filter(date_publication__lte=now).annotate(Count('coments')).order_by(ordering)
    paginator = Paginator(queryset, 4)
    context = all_paginator(request, paginator)
    context.update({'ordering': ordering})

    return render_to_response('blog.html', context)


def detail(request, id_article):
    today = datetime.date.today()
    try:
        id_article = int(id_article)
    except ValueError:
        raise Http404()
    queryset = Article.objects.filter(date_publication__lte=today)
    article_detailed = get_object_or_404(queryset, pk=id_article)
    article_coments = Coments.objects.filter(article=id_article, path__regex=r"^\d{8,120}$").order_by('path')
    if request.method == 'POST':
        form = ComentsForm(request.POST)
        if form.is_valid():
            parent_id = form.cleaned_data.get('parent_id')
            email = form.cleaned_data.get('email')
            message = form.cleaned_data.get('message')
            name = form.cleaned_data.get('name')
            new_coment = Coments(
                article_id=id_article,
                autor_coment=name,
                coment_text=message,
                mail_autor_coment=email
            )
            add_coment = {}
            if parent_id:
                new_coment.parent = Coments.objects.get(id=parent_id)
                add_coment["parent_id"] = new_coment.parent.id
                add_coment["path"] = new_coment.parent.path
            new_coment.save()
            add_coment.update({"id": new_coment.id,
                               "autor_coment": new_coment.autor_coment,
                               "date_coment": new_coment.date_coment,
                               "coment_text": new_coment.coment_text,
                               "mail_autor_coment": new_coment.mail_autor_coment,
                               "html_level": new_coment.html_level,
                               })
            return JsonResponse({'comentarii': add_coment, "result": "sucsess"})
        errors = {}
        for k in form.errors:
            errors[k] = form.errors[k][0]

        return JsonResponse({'erors': errors, 'result': 'error'})
    else:
        form = ComentsForm()

    paginator = Paginator(article_coments, 20)
    context = all_paginator(request, paginator)
    context.update({'article_detailed': article_detailed, 'form': form})
    return render_to_response('detail_article.html', context, context_instance=RequestContext(request))


def detail_coment(request, path, id_article):
    queryset = Coments.objects.filter(path__regex=r"^%s" % path).order_by('path')
    paginator = Paginator(queryset, 50)
    context = all_paginator(request, paginator)

    if request.method == 'POST':
        form = ComentsForm(request.POST)
        if form.is_valid():
            parent_id = form.cleaned_data.get('parent_id')
            email = form.cleaned_data.get('email')
            message = form.cleaned_data.get('message')
            name = form.cleaned_data.get('name')
            new_coment = Coments(
                article_id=id_article,
                autor_coment=name,
                coment_text=message,
                mail_autor_coment=email
            )
            add_coment = {}
            if parent_id:
                new_coment.parent = Coments.objects.get(id=parent_id)
                add_coment["parent_id"] = new_coment.parent.id
                add_coment["path"] = new_coment.parent.path
            new_coment.save()
            add_coment.update({"id": new_coment.id,
                               "autor_coment": new_coment.autor_coment,
                               "date_coment": new_coment.date_coment,
                               "coment_text": new_coment.coment_text,
                               "mail_autor_coment": new_coment.mail_autor_coment,
                               "html_level": new_coment.html_level,
                               "html_level_full": new_coment.html_level_full,
                               })
            return JsonResponse({'comentarii': add_coment, "result": "sucsess"})
        errors = {}
        for k in form.errors:
            errors[k] = form.errors[k][0]

        return JsonResponse({'erors': errors, 'result': 'error'})
    else:
        form = ComentsForm()
    context.update({'form': form})
    return render_to_response('coments.html', context, context_instance=RequestContext(request))


def page_home(request):
    return render_to_response('base.html')


def page_start(request):
    return HttpResponseRedirect(r'home/')


def page_about_me(request):
    return render_to_response('about_me.html')


def page_contacts(request):
    return render_to_response('contacts.html')

templates/about_me.html
{% extends "base.html" %}
{% block article %}
                        Обо мне
{% endblock %}

templates/base.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Test sait" />

    <title>{% block title %} Home page{% endblock %}</title>

    <link href="media/css/bootstrap.min.css" rel="stylesheet">
    <link href="media/templatemo_style.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="media/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="media/jquery.form.js"></script>
    <script type="text/javascript" src="media/jquery_my.js"></script>
    {% block skript %}{% endblock %}

</head>
<body>
<div id="templatemo_wrapper_outer">
    <div id="templatemo_wrapper_inner">
        {% block header_wrapper %}

        {% endblock %}

        {% block menu_wrapper %}
            <div id="templatemo_menu">
                <ul>
                    <li><a href="/blog_app/home" >Главная</a></li>
                    <li><a href="/blog_app/article" >Статьи</a></li>
                    <li><a href="/blog_app/about_me">О себе</a></li>
                    <li><a href="/blog_app/contacts">Контакты</a></li>
                </ul>
            </div> <!-- end of menu -->
        {% endblock %}

        {% block content %}
            <div id="templatemo_content_wrapper">
                <div class="templatemo_content margin_right_10">

                    {% block article %}
                        Этот сайт был создан в учебных целях
                    {% endblock %}
                </div>
            </div>
        {% endblock %}

        {% block footer_content %}

        {% endblock %}
    </div>
</div>
{% block footer %}
 <div id="templatemo_footer">
        Copyright © 2024 <a href="#">Your Company Name</a> | Designed by <a href="http://www.Ftemplate.ru" target="_parent">Free CSS Templates</a>
   	</div> <!-- end of footer -->

{% endblock %}

</body>
</html>

templates/blog.html
{% extends "base.html" %}

{% block title %}blog{% endblock %}


{% block article %}
    <div style="text-align: center">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}&sort={{ ordering }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}&sort={{ ordering }}">next</a>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-md-8 offset2"></div>
        <div class="col-md-4 " style="text-align: right;">Сортировать по:
            <span style="margin-left: 10px;"><a
                    {% if ordering == 'coments__count' %}
                        href="?sort=-coments__count"

                    {% elif ordering == '-coments__count' %}
                        href="?sort=coments__count"

                    {% else %}
                        href="?sort=coments__count"
                        style="color: #999"
                    {% endif %}  id="sort_coment">коментариям</a>
            </span>

            <span> | </span><a
                    {% if ordering == 'date_publication' %}
                        href="?sort=-date_publication"
                    {% elif ordering == '-date_publication' %}
                        href="?sort=date_publication"
                    {% else %}
                        href="?sort=date_publication"
                        style="color: #999"
                    {% endif %} id="sort_date" >дате</a>
        </div>
    </div>


{% for entry in page %}
            <div class="content_section">
           	  <div class="header_02"><a href='/blog_app/article/{{ entry.id }}/'>{{ entry.article_title }}</a></div>
              <div class="image_wrapper_01"><img src="media/images/templatemo_image_02.jpg" alt="image" /></div>
                <p>{{ entry.article_text|truncatechars:20 }} </p>
			  <div class="margin_bottom_20"></div>

				<div class="row">
                    <div class="col-sm-8">
					    <a href='/blog_app/article/{{ entry.id }}/' class="rc_btn_01">Прочитать статью</a>
                        <span style="margin-left: 20px;"><a href='/blog_app/article/{{ entry.id }}/'>коментариев:{{ entry.coments_set.count }}</a></span>
                    </div>
					<div class="col-sm-4 autor_article">Опубликованно: C5uJI
                        <span> | </span>{{ entry.date_publication }}</div>

				</div>

                <div class="cleaner"></div>
            </div>
{% endfor %}

        	<div class="margin_bottom_40"></div>
        </div> <!-- end of content -->

{% endblock %}

templates/coments.html
{% extends "base.html" %}
{% block skript %}
    <script>
        function value_parent(id){
            document.getElementsByName("parent_id")[0].value=id;
        }
    </script>
{% endblock %}


{% block article %}
    <div id="all_coments">
        {% for empty in page %}
            <div class="coment" style="margin:0 0 20px {{ empty.html_level_full }}" id="coment_{{ empty.id }}">
                {{ empty.autor_coment }}:
                <div style="padding-left: 50px">{{ empty.coment_text }}</div>
                <div>
                    {{ empty.date_coment }}
                    <span> | </span> <a href="#metka" onclick="value_parent({{ empty.id }})">ответить</a>
                    {% if  empty.level >= 30 %}
                        <span> |
                            <a href="/blog_app/detail_coment/{{ empty.path }}/{{ empty.article.id }}" style="text-align: right;">Прочитать ветку</a>
                        </span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>


    <div>
            <a name=metka></a>
                <form action="" method="post" name="ComentsForm" id="coment_form" >
                    {% csrf_token %}
                    {{ form.parent_id }}
                   <div class="row">
                       <div class="col-sm-1"><label for="id_name">Имя:</label></div>
                       <div class="col-sm-11">{{ form.name }}</div>
                   </div>
                    <div class="row">
                    <div class="col-sm-1"><label for="id_email">Почта:</label></div>
                       <div class="col-sm-11">{{ form.email }}</div>
                    </div>
                    <div class="row">
                    <div class="col-sm-1"><label for="id_message">Текст:</label></div>
                        <div class="col-sm-11">{{ form.message }}</div>
                    </div>
                    <div class="row">
                    <div class="col-sm-1 offset"></div>
                       <div class="col-sm-11" > <a href='#on' class="rc_btn_01" id="test">Отправить коментарий</a></div>
                    </div>

                </form>
            </div>
        </div>
{% endblock %}

templates/contacts.html
{% extends "base.html" %}
{% block article %}
                        мои контакты
                    {% endblock %}

templates/detail_article.html
{% extends "base.html" %}
{% block skript %}<script>
function value_parent(id){
    document.getElementsByName("parent_id")[0].value=id;

}


    </script>
{% endblock %}


{% block article %}

<div id="content">
    <div class="post">
        <div class="row">
            <div class="col-sm-10">{{ article_detailed.date_publication }}</div>
            <div class="col-sm-2">Posted by C5uJI</div>
        </div>
        <div class="header_02">{{ article_detailed.article_title }}</div>
        <div class="article">
            <img src="media/images/templatemo_image_02.jpg" alt="" class="image_wrapper_01" />
            {{ article_detailed.article_text }}</div>

            <div class="coments header_02">Коментарии к статье: </div>

                    <div style="text-align: center">
                        {% if page.has_previous %}
                            <a href="?page={{ page.previous_page_number }}&sort={{ ordering }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page.number }} of {{ page.paginator.num_pages }}.
                        </span>

                        {% if page.has_next %}
                            <a href="?page={{ page.next_page_number }}&sort={{ ordering }}">next</a>
                        {% endif %}
                    </div>



                <div id="all_coments">
                    {% for empty in page %}
                        <div class="coment" style="margin:0 0 20px {{ empty.html_level }}" id="coment_{{ empty.id }}">
                            {{ empty.autor_coment }}:
                            <div style="padding-left: 50px">{{ empty.coment_text }}</div>
                            <div>
                                {{ empty.date_coment }}
                                <span> | </span> <a href="#metka" onclick="value_parent({{ empty.id }})">ответить</a>
                                {% if  empty.level >= 15 %}
                                    <span> |
                                        <a href="/blog_app/detail_coment/{{ empty.path }}/{{ empty.article.id }}" >Прочитать ветку</a>
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>



        <div>
            <a name=metka></a>
                <form action="" method="post" name="ComentsForm" id="coment_form" >
                    {% csrf_token %}
                    {{ form.parent_id }}
                   <div class="row">
                       <div class="col-sm-1"><label for="id_name">Имя:</label></div>
                       <div class="col-sm-11">{{ form.name }}</div>
                   </div>
                    <div class="row">
                    <div class="col-sm-1"><label for="id_email">Почта:</label></div>
                       <div class="col-sm-11">{{ form.email }}</div>
                    </div>
                    <div class="row">
                    <div class="col-sm-1"><label for="id_message">Текст:</label></div>
                        <div class="col-sm-11">{{ form.message }}</div>
                    </div>
                    <div class="row">
                    <div class="col-sm-1 offset"></div>
                       <div class="col-sm-11" > <a href='#on' class="rc_btn_01" id="test">Отправить коментарий</a></div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}